# Generated by Django 2.0.5 on 2018-05-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20180522_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='modified_date',
            new_name='modification_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='modified_date',
            new_name='modification_date',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='modified_date',
            new_name='modification_date',
        ),
    ]
