# Generated by Django 2.0.5 on 2018-06-01 17:21

from django.db import migrations, models
import library_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20180522_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, validators=[library_app.validators.validate_isbn]),
        ),
    ]
