# Generated by Django 2.0.6 on 2018-06-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-creation_date']},
        ),
    ]
