# Generated by Django 2.0.6 on 2018-06-04 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_auto_20180604_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Book'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to=settings.AUTH_USER_MODEL),
        ),
    ]
