# Generated by Django 2.0.6 on 2018-06-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0010_auto_20180605_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryUser',
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='Borrowing',
            name='borrower',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to='library_app.LibraryUser'),
        ),
        migrations.AlterField(
            model_name='Borrowing',
            name='lender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lender', to='library_app.LibraryUser'),
        ),
        migrations.AlterField(
            model_name='Reservation',
            name='reserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to='library_app.LibraryUser'),
        ),
    ]
