# Generated by Django 2.0.6 on 2018-06-25 16:40

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def add_library_users_to_existing_users(apps, schema_editor):

    User = apps.get_model('auth', 'User')
    LibraryUser = apps.get_model('library_app', 'LibraryUser')

    for user in User.objects.all():
        try:
            user.libraryuser
        except ObjectDoesNotExist:
            LibraryUser.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_auto_20180625_1633'),
    ]

    operations = [
        migrations.RunPython(add_library_users_to_existing_users),
    ]
