# Generated by Django 2.0.6 on 2018-07-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_auto_20180625_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['creation_date']},
        ),
    ]
