# Generated by Django 2.0.6 on 2018-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_auto_20180717_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
